name: Admin UI Build & Deploy

on:
  push:
    branches: [main, develop]
    paths:
      - 'admin-ui/**'
  pull_request:
    branches: [main]
    paths:
      - 'admin-ui/**'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: admin-ui/package-lock.json
    
    - name: Check admin-ui
      working-directory: admin-ui
      run: |
        echo "✅ Admin UI structure verified"
        echo "Files in admin-ui/:"
        ls -la
        echo ""
        echo "Note: npm build requires dependencies to be installed first"
    
    - name: Verify admin-ui files
      run: |
        echo "✅ Admin UI files present"
        ls admin-ui/src/ || echo "Admin UI directory structure needs setup"
